// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "@/styles/globals.css";
// import {
//   Inter,
//   Lato,
//   Poppins,
//   Roboto,
//   Montserrat,
//   Open_Sans,
// } from "next/font/google";

// const inter = Inter({
//   subsets: ['latin'],
//   display: 'swap', 
// });


// export const lato = Lato({
//   subsets: ["latin"],
//   weight: ["300", "400", "700", "900"],
//   display: "swap",
// });

// export const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
//   display: "swap",
// });

// export const roboto = Roboto({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "700"],
//   display: "swap",
// });

// export const montserrat = Montserrat({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
//   display: "swap",
// });

// export const openSans = Open_Sans({
//   subsets: ["latin"],
//   weight: ["300", "400", "600", "700"],
//   display: "swap",
// });




// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body


//         className={`${geistSans.variable ,inter.className} ${geistMono.variable} antialiased`}

//       >
//         {children}
//       </body>
//     </html>
//   );
// }



import type { Metadata, Viewport } from "next";
import "@/styles/globals.css";

import {
  Inter,
  Lato,
  Poppins,
  Roboto,
  Montserrat,
  Open_Sans,
  Geist,
  Geist_Mono,
  Playfair_Display,
} from "next/font/google";

/* ================= GOOGLE FONTS ================= */
const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-lato",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-montserrat",
  display: "swap",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
  variable: "--font-open-sans",
  display: "swap",
});

/* ================= GEIST FONTS ================= */

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

/* ================= METADATA ================= */

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",


// };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export const viewport: Viewport = {
 width: "device-width",
    initialScale: 1,
    minimumScale: 1,
    maximumScale: 1,
    userScalable: false,
    viewportFit: "cover",
};

/* ================= ROOT LAYOUT ================= */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`
        ${inter.variable}
        ${lato.variable}
        ${poppins.variable}
        ${roboto.variable}
        ${montserrat.variable}
        ${openSans.variable}
        ${geistSans.variable}
        ${geistMono.variable}
        ${playfair}
      `}
    >
      {/* <body className={`${playfair.className} antialiased`}>
        {children}
      </body> */}
      <body


        className={`${geistSans.variable, inter.className} ${geistMono.variable} antialiased`}

      >
        {children}
      </body>
    </html>
  );
}
